name: Build and Run Docker Image

on:
  push:
    branches:
      - main  # Adjust the branch name if necessary

jobs:
  build-and-run:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_PASSWORD }}

    - name: Build Docker image
      run: docker build -t akhatri772/vocalai .

    - name: Run Docker container
      run: docker run -d -p 8080:80 akhatri772/vocalai

    - name: Verify the container is running
      run: docker ps

    - name: Curl the application endpoint
      run: curl http://localhost:8080

    - name: Stop Docker container
      run: docker stop $(docker ps -q --filter ancestor=akhatri772/vocalai)

    - name: Logout from Docker Hub
      run: docker logout
